CREATE TABLE IF NOT EXISTS DM_DEVICE_CERTIFICATE (
  ID                    BIGSERIAL NOT NULL PRIMARY KEY,
  SERIAL_NUMBER         VARCHAR(500) DEFAULT NULL,
  CERTIFICATE           BYTEA DEFAULT NULL,
  TENANT_ID INTEGER DEFAULT 0,
  USERNAME  VARCHAR(500) DEFAULT NULL
);