CREATE TABLE DM_DEVICE_CERTIFICATE (
  ID                    NUMBER(10) NOT NULL,
  SERIAL_NUMBER         VARCHAR2(500) DEFAULT NULL,
  CERTIFICATE           BLOB DEFAULT NULL,
  TENANT_ID NUMBER(10) DEFAULT 0,
  USERNAME  VARCHAR2(500) DEFAULT NULL,
  PRIMARY KEY (ID)
)